services:
  - type: web
    name: flask-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn final:app
    envVars:
      - key: FLASK_ENV
        value: production
